version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    environment:
      IMAGE: "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
      TAG: "0.1.$CIRCLE_BUILD_NUM"

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Show Environment
          command: |
            env | sort

      - run:
          name: Add docker deb repository
          command: |
            apt update
            apt install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common
            curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
            add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

      - run:
          name: Install Docker client
          command: |
            apt update
            apt install -y docker-ce

      - run:
          name: Build docker image
          command: |
            docker build -f Dockerfile.build -t $(eval echo ${IMAGE}:${TAG}) .
            docker run --rm $(eval echo ${IMAGE}:${TAG}) | grep "This message shows that your installation appears to be working correctly"
